# ======================================================================
#
# Experiment-specific configurations
#
# ======================================================================

# No need to quote the strings in yaml files, but do so when special 
# characters are used. More importantly, even if they are quoted here,
# they still need to be quoted again when used in the "shell" derivative.
input:
  pepfile_path: /Users/yi-che/Dropbox (Princeton)/phd/phd-data/analyses/alu_imaging/test-snakemake/raw_nd2/project_config.yaml
  experiment_type: movie
  samplesheet_path: /Users/yi-che/Dropbox (Princeton)/phd/phd-data/analyses/alu_imaging/test-snakemake/raw_nd2/samplesheet.csv
  raw:
    base_dir: /Users/yi-che/Dropbox (Princeton)/phd/phd-data/analyses
    subdir_name: test-snakemake
    ext: nd2

build_imagelist:
  nafilter: strict
  patch: True
  verbose: True

segment_nuclei_in_time:
  channel: sfGFP

piv:
  pkg_path: "external/MatPIV-1.7"
  channel: miRFP670
  movie_meta:
    PIXELSIZE: 0.135
    DT: 0.5
    LAGS_EXPRESSION: "unique(ceil(logspace(0,log10(50),15)))" 
  protocol: matpiv_v2
  protocol_configs:
    matpiv_v2:
      PREPROCESS:
        BACK: 210
      PIV:
        WINSIZE: 16
        OVERLAP: 0.75
        MODE: 'single'
      FILTERS:
        SNR: 1.1
        PKH: 0.3
        GLOBAL: 3

# ======================================================================
#
# Platform-specific configurations
#
# ======================================================================