# ======================================================================
#
# Experiment-specific configurations
#
# ======================================================================

# No need to quote the strings in yaml files, but do so when special 
# characters are used. More importantly, even if they are quoted here,
# they still need to be quoted again when used in the "shell" derivative.
input:
  pepfile_path: /tigress/yichec/data/microscopy/2023a/test-snakemake/project_config.yaml
  samplesheet_path: /tigress/yichec/data/microscopy/2023a/test-snakemake/samplesheet.csv
  experiment_type: movie
  raw:
    base_dir: /tigress/yichec/data/
    # write in one line, with single quotes, and write \/ for forward
    # slash, write \ for backslash
    common_pattern: 'microscopy\/\d{4}[a-d]\/.*'
    subdir_name: test-snakemake
    ext: nd2

build_imagelist:
  nafilter: strict
  patch: True
  verbose: True

segment_nuclei_in_time:
  channel: sfGFP

normalize_intensity:
  background: 400

piv:
  pkg_path: "external/MatPIV-1.7"
  channel: 
    - miRFP670
    - sfGFP
  movie_meta:
    PIXELSIZE: 0.135
    DT: 0.5
    LAGS_EXPRESSION: "unique(ceil(logspace(0,log10(50),15)))" 
  protocol: matpiv_v2
  protocol_configs:
    matpiv_v2:
      CONFIG:
        PREPROCESS:
          BACK: 210
        PIV:
          WINSIZE: 16
          OVERLAP: 0.75
          MODE: 'single'
        FILTERS:
          SNR: 1.1
          PKH: 0.3
          GLOBAL: 3

# ======================================================================
#
# Platform-specific configurations
#
# ======================================================================
