# ======================================================================
#
# Experiment-specific configurations
#
# ======================================================================

# No need to quote the strings in yaml files, but do so when special 
# characters are used. More importantly, even if they are quoted here,
# they still need to be quoted again when used in the "shell" derivative.
input:
  samplesheet_path: /Users/yi-che/repository/phd-analysis/abc-mobility/data/example_nd2/samplesheet.csv
  image_path:
    dir: /Users/yi-che/repository/phd-analysis/abc-mobility/data/example_nd2
    glob: '*.nd2'
    regex: 'Well(?P<WellID>[A-H]\d{2})_Fov(?P<FovID>\d{3}).nd2'
  datefmt: 
  # channels has to be in the order as how they present in the raw file
  channels: 
    - oc: 640 nm
      fluoro: miRFP670
      colormap: magenta
      background: 400 
    - oc: 488 nm
      fluoro: sfGFP
      colormap: green
      background: 400
    - oc: 405 nm
      fluoro: BFP
      colormap: blue
      background: 400
  bitdepth: 16

parse_metadata:
  nafilter: strict
  verbose: True
  patch: True


build_imagelist:
  nafilter: strict
  patch: True
  verbose: True

segment_nuclei_in_time:
  channel: sfGFP
  diameter: 100
  downsample: 2


normalize:
  structure:
    - nucleus
    - nucleoplasm
  method: zscore
  # nested as dict. leave it empty if not needed
  method_kwargs:


normalize_intensity:
  background: 400


predict_nucleoli:
  channel: BFP
  model_name: u2os_nucleoli_bfp_v1

measure:
  structure:
    - nucleus
    # - nucleoplasm

piv:
  pkg_path: "external/MatPIV-1.7"
  channel: 
    - miRFP670
    - sfGFP
  movie_meta:
    PIXELSIZE: 0.135
    DT: 0.5
    LAGS_EXPRESSION: "unique(ceil(logspace(0,log10(50),15)))" 
  protocol: matpiv_v2
  protocol_configs:
    matpiv_v2:
      CONFIG:
        PREPROCESS:
          BACK: 210
        PIV:
          WINSIZE: 16
          OVERLAP: 0.75
          MODE: 'single'
        FILTERS:
          SNR: 1.1
          PKH: 0.3
          GLOBAL: 3

msnd:
  channel: miRFP670
  weight_channel: sfGFP

resources:
  classifiers:
    u2os_nucleoli_bfp_v1:
      url: 'https://www.dropbox.com/s/ryoma1qvklinxn6/u2os_nucleoli_bfp_v1.ilp?dl=1'
